### PR TITLE
Added ru translation for version 1.0.0

### PR DESCRIPTION
**Pull request by aishek**

### CODE REVIEW

**Comment by olivierlacan** [comment]
Thanks @aishek!

**Comment by olivierlacan** [comment]
@aishek I have to revert your changes. You need to adapt this version to the new layout system. Not simply convert it within the old Markdown syntax. Please look at the English version for 1.0.0 as an example.

**Comment by aishek** [comment]
@olivierlacan it's my bad, sorry.

I've opened another pull request #185 for Russian translation. Let's continue there?

**Comment by olivierlacan** [comment]
@aishek No problem. :-)

**Pull request merged**
