### PR TITLE
Cherry Picked Chinese Translation

### PR DESCRIPTION
**Pull request by tianshuo**
Made a merge mistake in #87
Resubmitting Translation

This was original comment:
> Hi, we found your repo useful for our team, and have faithfully translated it into Chinese for those who have difficulty reading English. I have written the translation in Simplified Chinese(简体字), and machine translated it into Traditional Chinese(繁体字), thus there may be slight problems in the latter version.

> Note that we will be using the date format you have provided and English tags for catagorizing which kinds of changes have happened.

### CODE REVIEW

**Comment by tianshuo** [comment]
Hi, is anyone going to merge this PR?

**Comment by olivierlacan** [comment]
@tianshuo Yes.

**Comment by tianshuo** [comment]
So when will http://keepachangelog.com be updated?

**Comment by olivierlacan** [comment]
@tianshuo When I'm no longer on vacation ;-)

**Pull request merged**
