### PR TITLE
Add Slovenian translation for 1.0.0 and 1.1.0

### PR DESCRIPTION
**Pull request by petk**
This adds Slovenian (sl_SI) translation for the 1.0.0 and 1.1.0 versions.

### CODE REVIEW

**Comment by olivierlacan** [comment]
Thanks so much @petk, is there any chance you could tag a fellow Slovenian speaker for a quick review?

**Comment by petk** [comment]
Hm, that will be difficult. I'm not sure I'll find one that can do that just like that. :D Otherwise, I've checked these translations, so no worries. I'm native speaker. I've also translated version 0.3.0 in the past if it helps in any way.

**Comment by petk** [comment]
One additional fix has been committed to pull request. I've also asked around a bit if anyone else can review this...

**Comment by olivierlacan** [comment]
Sounds good. 😊

**Pull request merged**
