### PR TITLE
sv/1.0.0 - Fix link

### PR DESCRIPTION
**Pull request by magol**

### CODE REVIEW

**Comment by olivierlacan** [comment]
Thanks. I missed that second link issue.

**Comment by olivierlacan** [comment]
`bundle exec middleman build --verbose` is still failing on sv/1.0.0/index.html.haml` for some reason: 

```
== Request: /sv/1.0.0/index.html
       error  build/sv/1.0.0/index.html
can't modify frozen String
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/engine.rb:131:in `rescue in render'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/engine.rb:128:in `render'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/renderers/haml.rb:35:in `evaluate'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/renderers/haml.rb:9:in `render'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/file_renderer.rb:79:in `render'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/template_renderer.rb:186:in `_render_with_all_renderers'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/template_renderer.rb:149:in `block in render'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications.rb:166:in `instrument'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/template_renderer.rb:148:in `render'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/resource.rb:154:in `render'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/rack.rb:112:in `process_request'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/rack.rb:66:in `block in call'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/rack.rb:65:in `catch'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/rack.rb:65:in `call'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/extensions/minify_javascript.rb:55:in `call'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/extensions/minify_css.rb:63:in `call'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/htmlcompressor-0.2.0/lib/htmlcompressor/rack.rb:36:in `call'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-autoprefixer-2.7.0/lib/middleman-autoprefixer/extension.rb:48:in `call'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/core_extensions/inline_url_rewriter.rb:74:in `call'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/mock.rb:74:in `request'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/mock.rb:56:in `get'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/builder.rb:230:in `block in output_resource'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications.rb:166:in `instrument'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/builder.rb:223:in `output_resource'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/builder.rb:137:in `map'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/builder.rb:137:in `output_resources'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/builder.rb:129:in `output_files'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/builder.rb:71:in `block in run!'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications.rb:166:in `instrument'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/builder.rb:70:in `run!'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.10/lib/middleman-cli/build.rb:80:in `block in build'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications.rb:166:in `instrument'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.10/lib/middleman-cli/build.rb:79:in `build'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.10/bin/middleman:72:in `<top (required)>'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/middleman:23:in `load'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/middleman:23:in `<top (required)>'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/Users/olivierlacan/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/olivierlacan/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

**Comment by olivierlacan** [comment]
The problem is that `haml/engine.rb:131` is actually receiving code it's running `eval` on and for some reason the code for this specific template is different from all the others in that the front matter variables at the top are not ignored in the same way.

It's very strange. I think I'm going to update Haml and see what happens.

**Comment by olivierlacan** [comment]
Strange, after an update the error becomes the following: 

```
Haml::TempleEngine: Option :context is invalid
       error  build/sv/1.0.0/index.html
/Users/olivierlacan/Development/perso/keep-a-changelog/source/sv/1.0.0/index.html.haml:2: syntax error, unexpected ';'
; _hamlout.buffer << ("descrip...
 ^
/Users/olivierlacan/Development/perso/keep-a-changelog/source/sv/1.0.0/index.html.haml:7: syntax error, unexpected ';'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/haml-5.0.1/lib/haml/engine.rb:128:in `rescue in render'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/haml-5.0.1/lib/haml/engine.rb:125:in `render'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/renderers/haml.rb:35:in `evaluate'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/tilt-2.0.7/lib/tilt/template.rb:109:in `render'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/renderers/haml.rb:9:in `render'
/Users/olivierlacan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.14/lib/middleman-core/file_renderer.rb:79:in `render'
```

**Comment by magol** [comment]
I installed the tools needed to test the generation. I figured out that the problem was that my file was formatted as `UTF-8 with BOM` and the rest of the files was formatted without `BOM`. 
See PR #174

**Comment by olivierlacan** [comment]
I should have known it was encoding! I need a t-shirt with that on it. 😄

**Pull request merged**
