### PR TITLE
Clean code

### PR DESCRIPTION
**Pull request by Mortiferr**
Cleaned up the code (dirtymarkup.com is a wonderful tool) so that it's more readable.

### CODE REVIEW

**Comment by olivierlacan** [comment]
@nbibler can correct me but this page is generated so you changing it will not amount to much since the publishing process with mess it up again. A better solution would be to run a beautifier in the publishing task to clean the code after it's generated.

**Comment by nbibler** [comment]
The HTML _is_ generated; that is correct. When generated, it is minified and crushed down to a somewhat un-human-readable format _on purpose_. The removal of whitespace reduces the total file size of the document, thereby reducing the network load on the user and improving the load time of the site. If the goal were to generate human-readable HTML, then we could simply [disable the minification and uglification](https://github.com/olivierlacan/keep-a-changelog/blob/master/config.rb#L75-L79) part of the build process and it would generate "pretty" HTML.

**Comment by Mortiferr** [comment]
I see.

**Comment by olivierlacan** [comment]
Sidenote: I will probably disable minification and uglification. I don't think it makes that much of a difference in such a small document, and I like clean source, even on the client.

**Comment by Mortiferr** [comment]
Awesome

**Pull request closed without merging**
