### PR TITLE
Change some Japansese expressions to better ones.

### PR DESCRIPTION
**Pull request by munierujp**
|English|Before|After|Example of use|
|---|---|---|---|
|human-friendly|人間に優しい|ヒューマンフレンドリーな|[1](https://ci.nii.ac.jp/naid/110004788357)|
|issue|懸念事項|Issue|[2](https://help.github.com/ja/articles/about-issue-and-pull-request-templates)|
|contributors|貢献者|コントリビューター|[3](https://help.github.com/ja/articles/using-templates-to-encourage-high-quality-issues-and-pull-requests-in-your-repository)|

### CODE REVIEW

**Comment by munierujp** [comment]
@tsubakimoto Could you review this?

**Comment by tsubakimoto** [comment]
Hi @munierujp , thank you for your suggestions.
I think no problem.

**Comment by munierujp** [comment]
@tsubakimoto Thak you!

**Comment by munierujp** [comment]
@olivierlacan Hi, I've changed some Japansese expressions to better ones. and it was reviewd by Japanese document author (@tsubakimoto). Could you merge it?

**Comment by olivierlacan** [comment]
@munierujp Sorry for the delay, thanks so much for your contribution :-)

**Pull request merged**
