### PR TITLE
Improve Spanish translation

### PR DESCRIPTION
**Pull request by dgdavid**
Hi everyone!

I am making this PR in order to improve a little the Spanish translation. I would like to have the feedback of @ZeliosAriex and @leocabeza (who made current Spanish translations) apart from someone else that wants to help.

I also want to discuss about some specific words and achieve an agreement about which could be the best translation for them

* **curated**; in the context of  _a file which contains a curated, chronologically ordered list_ I believe that `saneada` or `limpia`  is the meaning of this word. However, I am not sure about if we should include this translation in the sentence. Probably _un fichero que contiene una lista conológicamente ordeanda_ could be enough.

* **deprecations**; this is a difficult word to translate.  I have no problem to keep it as it in the Spanish version, maybe emphasizing it. But if we want to translate it to Spanish, we can not use `deprecación` or `deprecaciones` because it is a Spanish word with a different meaning ([see RAE definition](http://dle.rae.es/?id=CFmWKG6)). In fact, other guys already discussed this topic (see  for example [1](https://twitter.com/pedrogk/status/855484262958673921),  [2](https://twitter.com/seppo0011/status/726089723647823873) or [3](https://twitter.com/arturotena/status/596737511579209728) at Twitter).

  So, I will propose to use `obsoleto/a` or `funcionalidad(es) sin soporte`. Also `desaprobaciones` could be an option, but honestly it sounds weird to me.

* **contributors**; while `contribuyente` could be used as the adjective `contributor`, as a noun (according to [RAE definition](http://dle.rae.es/?id=AeTqHgU)) is the person that has to pay a tax. So, IMO, is better to use `colaboradores` in this context.

* **mention**; in the `Guides principles` I prefer to use `Indicar` over `Mencionar`.

* **pull request**; it could be translated as `petición de cambios`, but IMO it is not necessary.

Apart from this, I also agree with @callumlocke about the issue with ["Confusing dates"](https://github.com/olivierlacan/keep-a-changelog/issues/178) paragraph and it could be written simpler. Even more, something similar to the one addressed in the previous version (0.3.0) could be more clear:

  **`en:`**
  > The format YYYY-MM-DD must be used. It is a [ISO standard](http://www.iso.org/iso/home/standards/iso8601.htm), international, [sensible](https://xkcd.com/1179/) and language independent.

  **`es:`**
  > Se debe usar el formato de fecha AAAA-MM-DD. Es un [estándar ISO](http://www.iso.org/iso/home/standards/iso8601.htm), internacional, [sensato](https://xkcd.com/1179/) e independiente del lenguaje.

Finally, I must admit that the paragraph [Ignoring deprecations](http://keepachangelog.com/en/1.0.0/#ignoring-deprecations) is a little complicated for me to understand.

PS: I am also going to do a friendly ping to @backpackerhh because I know he has free time and I am pretty sure that he can give us a good review.

### CODE REVIEW

**Comment by leocabeza** [comment]
Hi @dgdavid.

- About **curated**, it's a though one, but _Lista cronológicamente ordenada_ sounds good enough to me. 
- **deprecations**, In mi opinion, the word `obsoleto/a`makes more sense in the software lingo.
- **contributors** I agree that `colaboradores` is the right word in this context.

**Comment by olivierlacan** [comment]
@dgdavid I've updated the Confusing Dates section in English 1.0.0: c81765b

Let me know how it works for you.

**Comment by dgdavid** [comment]
@olivierlacan,

It sounds better to me :)

I just updated the PR after synced my fork.

**Comment by olivierlacan** [comment]
Thanks @dgdavid!

**Pull request merged**
