### PR TITLE
Add github-changes reference

### PR DESCRIPTION
**Pull request by fixe**

### CODE REVIEW

**Comment by elyscape** [comment]
I'm not convinced that this is a good idea.  Isn't the whole point of the project that the changelog should be something more than just the output of a script?  Yes, PR titles are more useful than commit summaries for changelog purposes, but they still are likely to be less than ideal, especially when you consider that anyone can make a PR and some of them may have weird names.

**Comment by fixe** [comment]
@elyscape if the tool supported something like picking only PRs labeled with `changelog` and if the owners curated the titles I think the tool would be a good fit.

We use it in several projects and it works perfectly. See [example](https://github.com/lalitkapoor/github-changes/blob/master/CHANGELOG.md).

**Comment by skywinder** [comment]
@elyscape the author of the project can change name of the any issues. (Pull request is specific type of issue also). So it's not a problem.

By the way, I create similar pull request: #63 
This tool manages not only pull request, but closed issues also.

It exclude  issues, labeled by default GitHub labels `question duplicate invalid wontfix` by default.
And you can manage, which issues and pull requests will be added to changelog.

**Comment by olivierlacan** [comment]
See https://github.com/olivierlacan/keep-a-changelog/pull/63#issuecomment-145990290 for my reasoning on this. I'm not saying no forever, I just don't think it's a good idea for now.

**Pull request closed without merging**
