### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by olivierlacan**
image

So far a work in progress but exciting things coming:
- anchor links on headers are back
- simplified language navigation
- notice when the currently read translation isn't for the latest English version (to prompt translation contributions and ensure people don't read an outdated version without noticing)

More to come:
- responsive design legible at small viewport sizes
- better navigation between sections with a table of contents menu
- better typography
- clearer sub-sections

### CODE REVIEW

**Comment by olivierlacan** [comment]
Latest iteration of the design since @tylerfortune8 joined the effort. 

image

This is super work in progress, but I like where it's heading.

**Comment by olivierlacan** [comment]
Massive changes since the last visual update: 

image

**Comment by magol** [comment]
@olivierlacan  Is it any staging version of this online where we can see current status of the new version?

**Comment by olivierlacan** [comment]
@magol Nope, you can check the branch though.

**Pull request merged**
