### PR TITLE
Update Swedish translation to v1.1

### PR DESCRIPTION
**Pull request by magol**

### CODE REVIEW

**Comment by janderssonse** [comment]
Looks good to me @magol . @olivierlacan Native Swedish here, I approve of @magol s updated v1.1-base. I think it could be merged.

**Comment by olivierlacan** [comment]
Thanks @janderssonse and @magol !

**Comment by magol** [comment]
I realize that I ironically forgot to add information about my update to 1.1 for Swedish in CHANGELOG.md

**Comment by olivierlacan** [comment]
@magol I'll add it :-D

**Pull request merged**
