### PR TITLE
Change log = changelog

### PR DESCRIPTION
**Pull request by Mortiferr**
https://en.wikipedia.org/wiki/Changelog
According to Wikipedia changelog should be spelled changelog not change (space) log. `Change log` is technically correct but I think changelog looks better and it is more widely accepted. 

Love your project and I intend to help out where possible.

### CODE REVIEW

**Comment by svetlyak40wt** [comment]
Nice fix.

**Comment by olivierlacan** [comment]
Thank you for that, this has been killing me.

**Comment by Mortiferr** [comment]
No problem, love to help when I can.

**Comment by Mortiferr** [comment]
k

**Comment by Mortiferr** [comment]
Are pull requests ever going to be pushed live?

**Comment by olivierlacan** [comment]
Not before I figure out a plan for versioning releases and syncing up translations.

**Comment by Mortiferr** [comment]
:+1:

**Comment by roalz** [comment]
Any news on "pushing live" pull requests? Do you need any comment/suggestion for versioning? (=> semver.org :-)

**Comment by olivierlacan** [comment]
@roalz No the branch is nearly done, I just have to find the time to finalize it.

**Comment by olivierlacan** [comment]
@roalz You can see and review the existing work here #110

**Comment by roalz** [comment]
Great! :+1:

**Comment by olivierlacan** [comment]
All right. Versioning is out. Do you believe I should bump to version to 0.4.0 in order to add this change (since it will likely impact all translations)?

**Comment by Mortiferr** [comment]
Not exactly sure how versioning works on this repo, do you have any docs or are you just following semver?

**Comment by olivierlacan** [comment]
I'm attempting to follow logic and SemVer. If we change the English version in a significant ways all the other translations become slightly different immediately so I think every formatting/typo change should provoke a patch version bump while semantic (meaning) changes of the document or added sections should provoke a minor version bump. 

Any "breaking" change that would render existing changelogs based on the latest version clearly incompatible should result in a major version bump. 

Make sense?

**Comment by Mortiferr** [comment]
Sounds pretty logical to me. So bumping the version to 0.4.0 sounds good.

**Comment by olivierlacan** [comment]
@Mortiferr Can you rebase master and turn this into the first draft of version 0.4.0 please?

**Comment by vmuriart** [comment]
Don't forget the [first line in the changelog](https://github.com/olivierlacan/keep-a-changelog/blob/24b18124f446750e4097b5d4a098b2dd6d78c4a5/CHANGELOG.md#change-log)

**Comment by Mortiferr** [comment]
Will rebase soon

**Comment by olivierlacan** [comment]
Oh wow, I really thought I had merged this ages ago. I'm sorry @Mortiferr.

**Comment by Mortiferr** [comment]
You're a busy man, no worries.

**Comment by olivierlacan** [comment]
@Mortiferr I found a way to easily make changes and finally start work on 0.4.0 so we'll merge this PR into that. :-)

**Comment by beatngu13** [comment]
There's one "change log(s)" left in the section ["What about yanked releases"](https://github.com/Mortiferr/keep-a-changelog/blob/bfb5f160e90dd8944c85e4ad6f2c0c8b92d98976/README.md#what-about-yanked-releases): "Often these versions don't even appear in _change logs_."

**Comment by olivierlacan** [comment]
Fixed independently. Thank you very much for the suggestion. It was a bit too complicated to merge this since most of the changes ended up in 1.0.0.

**Pull request closed without merging**
