### PR TITLE
Updated Polish translation to v1.1

### PR DESCRIPTION
**Pull request by psztoch**

### CODE REVIEW

**Comment by olivierlacan** [comment]
Thanks @psztoch. Any chance you could solicit a Polish-speaking reviewer? 😅

**Comment by psztoch** [comment]
I am native from Poland.

I am interested in your initiative, but without #558, I do not see an optimistic future. :-)

**Comment by olivierlacan** [comment]
> I am native from Poland.

I'm native from France, but it never hurts to have a reviewer *if* you can find one. Otherwise no big deal.

I wouldn't agree that #558 is a blocker. It's not the goal of this project to provide tooling but your term translation index idea is interesting. One thing at time. 😸

**Comment by psztoch** [comment]
> > I am native from Poland.
> 
> I'm native from France, but it never hurts to have a reviewer _if_ you can find one. Otherwise no big deal.
I am trying to implement CHANGELOG.md in projects where I work. In my own interest, I will review the progress of work and Polish translations. ;-)

> I wouldn't agree that #558 is a blocker. It's not the goal of this project to provide tooling but your term translation index idea is interesting. One thing at time. 😸
From experience I know that a reference parser is very much needed as we introduce a broad standard.
Without it, everyone sooner or later implements the details differently.

**Comment by olivierlacan** [comment]
Thanks @psztoch!

**Pull request merged**
