### PR TITLE
Manage the static files with Middleman

### PR DESCRIPTION
**Pull request by nbibler**
This is a pull request for the `gh-pages` branch because GitHub won't let me create a Pull from my `master` to a non-existent `master` upstream. :frowning:

So @olivierlacan, you'll want to manually merge my `master` as yours. After that, work in `master` and going forward the site can be built and published with:

```
bundle exec rake deploy
```

My master still includes the _terrible_ French translation as an example. And there's currently no link on the index pages to jump between translations.

### CODE REVIEW

**Comment by monoman** [comment]
AFAIK, only the gh-pages branch is automatically published, why switch to
manual publication moving to an unneeded 'master'?

Rafael Teixeira
O..:.)oooo

**Comment by nbibler** [comment]
It's not really manual publication, per se. The middleman app builds the static files and automatically pushes to the `gh-pages` branch. The upsides of _not_ working directly on `gh-pages` and using the app are: minification, asset compression, fingerprinting, localization support, to name just a few.

**Comment by monoman** [comment]
Thanks @nbibler for the clarifications :+1:

**Comment by nbibler** [comment]
Sure :)

**Pull request merged**
