### PR TITLE
Adding breaks section as proposed in #41

### PR DESCRIPTION
**Pull request by danzilio**

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Or `Breaking`

**Comment by danzilio** [comment]
I'm not married to the name. I'd be fine with changing it to `Breaking`

**Comment by elyscape** [comment]
Yeah, I think `Breaking` is more clear.

**Comment by olivierlacan** [comment]
@elyscape Can you switch it to 'Breaking'?

**Comment by olivierlacan** [comment]
Going to close this. I meant `[BREAKING]` as a tag for any type of change. You could very well have:

```markdown
### Changed
- [BREAKING] This breaks backward compatibility.
```

or 

```markdown
### Added
- [BREAKING] This also breaks backward compability.
```

**Pull request closed without merging**
