### PR TITLE
Added bad changelog paragraph on inconsistency

### PR DESCRIPTION
**Pull request by RichardLitt**
Having an inconsistent changelog is bad. I feel this should be mentioned.

### CODE REVIEW

**Comment by olivierlacan** [comment]
It took me way too long to respond to this. I like it but we have to bump the minor for a change like this since it will require synchronization across translations. I’m actually surprised we didn’t already cover this. 

I think I’ll bump the minor on master and start focusing on that instead of patching 1.0.0. I’ll merge this as soon as that’s done.

**Comment by olivierlacan** [comment]
@RichardLitt Sorry for taking so long to get back to this. Do you mind moving this to a new `1.1.0` directory so it doesn't bump all the existing translations out of sync from 1.0.0. This can be the first change we make to the guidelines on the path to 2.0.

**Comment by RichardLitt** [comment]
@olivierlacan No worries! Pushed.

**Comment by RichardLitt** [comment]
Thanks, @olivierlacan.

**Comment by BONGKOTBUNSO** [comment]
> Having an inconsistent changelog is bad. I feel this should be mentioned.

**Review by BONGKOTBUNSO — APPROVED** [review]

**Review by BONGKOTBUNSO — COMMENTED** [review]
source/en/1.1.0/index.html.haml

**Pull request merged**
