### PR TITLE
Fix typo for zh-CN

### PR DESCRIPTION
**Pull request by lindexi**

### CODE REVIEW

**Comment by olivierlacan** [comment]
Do you mind describing the typo fix? Thank you.

**Comment by lindexi** [comment]
@olivierlacan In Chinese, the `哪些` means `what?` and the  `那些` means `those`

图片


图片

> 现行版本的GitHub发布不像哪些典型的大写文件
What typical capital files does the current version of GitHub publish like

> 现行版本的GitHub发布不像那些典型的大写文件
The current version of GitHub is not published like those typical capital files.

**Comment by lindexi** [comment]
@ olivierlacan Any Update?

**Review by Gaotianhe — APPROVED** [review]
It's OK.

**Comment by olivierlacan** [comment]
@Gaotianhe @lindexi Thanks a lot and sorry for the delay!

**Pull request merged**
