### PR TITLE
Swedish translation

### PR DESCRIPTION
**Pull request by magol**

### CODE REVIEW

**Comment by magol** [comment]
@devlead, @opinionmachine and @Paxxi , can you please review this to?

**Comment by olivierlacan** [comment]
Hey there, do you mind update your PR for the new folder structure? You'll have to move your `sv/` directory to the `/0.3.0/` directory and remove your changes to `layout.haml` since that's all dynamic now. Thanks!

**Comment by magol** [comment]
@olivierlacan I have updated the folder structure :-)

**Comment by olivierlacan** [comment]
Thank you @magol!

**Pull request merged**
