### PR TITLE
Add Japanese localization

### PR DESCRIPTION
**Pull request by tsubakimoto**
Hi. I Added Japanese localization.

### CODE REVIEW

**Comment by olivierlacan** [comment]
Hi @tsubakimoto and thank you so much for your work. Do you mind rebasing your commits into one squashed commit?

**Comment by tsubakimoto** [comment]
Hi @olivierlacan . ok.

**Comment by olivierlacan** [comment]
@tsubakimoto I forgot GitHub lets you Squash & Merge now so don't worry about it. Thanks so much for your contribution. 👍

**Comment by tsubakimoto** [comment]
Thanks @olivierlacan . Because I am not good at English, I expect the community to improve translation.

**Pull request merged**
